import { Materials } from "./types";

export const materialsAkrilka: Materials[] = [
  {
    id: "322",
    name: "A101",
    price: "20062",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A101_Glacier_White_.jpg",
    category: "akrilika",
    color: "белый",
    faktura: "монотонный",
  },
  {
    id: "323",
    name: "A005",
    price: "23322",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A005_Nocturne_.jpg",
    category: "akrilika",
    color: "черный",
    faktura: "монотонный",
  },
  {
    id: "324",
    name: "A120",
    price: "23322",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A120_Ivory_.jpg",
    category: "akrilika",
    color: "бежевый",
    faktura: "монотонный",
  },
  {
    id: "325",
    name: "A121",
    price: "23322",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A121_White_Sand_.jpg",
    category: "akrilika",
    color: "бежевый",
    faktura: "мелкие вкрапления",
  },
  {
    id: "326",
    name: "A122",
    price: "23322",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A122_Snow_Manka_.jpg",
    category: "akrilika",
    color: "",
    faktura: "мелкие вкрапления",
  },
  {
    id: "327",
    name: "A123",
    price: "23322",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A123_Steel_.jpg",
    category: "akrilika",
    color: "серый",
    faktura: "мелкие вкрапления",
  },
  {
    id: "328",
    name: "A125",
    price: "23322",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A125_Volcanic_Sand_.jpg",
    category: "akrilika",
    color: "коричневый",
    faktura: "мелкие вкрапления",
  },
  {
    id: "329",
    name: "A126",
    price: "23322",
    image:
      "../../public/CalcImages/StoneTypes/Akrilka/A126_Light_Concrete_.jpg",
    category: "akrilika",
    color: "светлосерый",
    faktura: "мелкие вкрапления",
  },
  {
    id: "330",
    name: "A127",
    price: "23322",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A127_Cortina_.jpg",
    category: "akrilika",
    color: "светлосерый",
    faktura: "мелкие вкрапления",
  },
  {
    id: "331",
    name: "A132",
    price: "23322",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A132_Iron_Grey_.jpg",
    category: "akrilika",
    color: "серый",
    faktura: "мелкие вкрапления",
  },
  {
    id: "332",
    name: "A133",
    price: "23322",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A133_Beton_White_.jpg",
    category: "akrilika",
    color: "бежевый",
    faktura: "мелкие вкрапления",
  },
  {
    id: "333",
    name: "A134",
    price: "23322",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A134_Beton_Light_.jpg",
    category: "akrilika",
    color: "бежевый",
    faktura: "мелкие вкрапления",
  },
  {
    id: "334",
    name: "A135",
    price: "23322",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A135_Beton_Grey_.jpg",
    category: "akrilika",
    color: "серый",
    faktura: "мелкие вкрапления",
  },
  {
    id: "335",
    name: "A137",
    price: "23322",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A137_Saint_White_.jpg",
    category: "akrilika",
    color: "бежевый",
    faktura: "мелкие вкрапления",
  },
  {
    id: "336",
    name: "A403",
    price: "23322",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A403_Ashes__.jpg",
    category: "akrilika",
    color: "светлосерый",
    faktura: "монотонный",
  },
  {
    id: "337",
    name: "A404",
    price: "23322",
    image:
      "../../public/CalcImages/StoneTypes/Akrilka/A404_Translucent_White_.jpg",
    category: "akrilika",
    color: "светлосерый",
    faktura: "монотонный",
  },
  {
    id: "338",
    name: "A411",
    price: "23322",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A411_Slancio_White_.jpg",
    category: "akrilika",
    color: "светлосерый",
    faktura: "мелкие вкрапления",
  },
  {
    id: "339",
    name: "A502",
    price: "23322",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A502_Everest_.jpg",
    category: "akrilika",
    color: "светлосерый",
    faktura: "мелкие вкрапления",
  },
  {
    id: "340",
    name: "A513",
    price: "23322",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A513_Edelwise_Neo_.jpg",
    category: "akrilika",
    color: "светлосерый",
    faktura: "мелкие вкрапления",
  },
  {
    id: "341",
    name: "A514",
    price: "23322",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A514_Edelwise_.jpg",
    category: "akrilika",
    color: "светлосерый",
    faktura: "мелкие вкрапления",
  },
  {
    id: "342",
    name: "A712",
    price: "23322",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A712_Snow_Lotus_.jpg",
    category: "akrilika",
    color: "светлосерый",
    faktura: "мелкие вкрапления",
  },
  {
    id: "343",
    name: "A715",
    price: "23322",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A715_King_Sand_.jpg",
    category: "akrilika",
    color: "коричневый",
    faktura: "мелкие вкрапления",
  },
  {
    id: "344",
    name: "A801",
    price: "23322",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A801_Arctic_White_.jpg",
    category: "akrilika",
    color: "серый",
    faktura: "мелкие вкрапления",
  },
  {
    id: "345",
    name: "A808",
    price: "23322",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A808_Dovetail_.jpg",
    category: "akrilika",
    color: "серый",
    faktura: "мелкие вкрапления",
  },
  {
    id: "346",
    name: "A811",
    price: "23322",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A811_Coal_.jpg",
    category: "akrilika",
    color: "черный",
    faktura: "мелкие вкрапления",
  },
  {
    id: "347",
    name: "A901",
    price: "23322",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A901_Mandarin_.jpg",
    category: "akrilika",
    color: "",
    faktura: "монотонный",
  },
  {
    id: "348",
    name: "A903",
    price: "23322",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A903_Sun_.jpg",
    category: "akrilika",
    color: "",
    faktura: "монотонный",
  },
  {
    id: "349",
    name: "A906",
    price: "23322",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A906_Hot_.jpg",
    category: "akrilika",
    color: "",
    faktura: "монотонный",
  },
  {
    id: "350",
    name: "A124",
    price: "25830",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A124_Robusta_.jpg",
    category: "akrilika",
    color: "коричневый",
    faktura: "мелкие вкрапления",
  },
  {
    id: "351",
    name: "A130",
    price: "25830",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A130_Soft_Grey_.jpg",
    category: "akrilika",
    color: "светлосерый",
    faktura: "мелкие вкрапления",
  },
  {
    id: "352",
    name: "A131",
    price: "25830",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A131_Dove_Grey_.jpg",
    category: "akrilika",
    color: "серый",
    faktura: "мелкие вкрапления",
  },
  {
    id: "353",
    name: "A201",
    price: "25830",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A201_Midnight_.jpg",
    category: "akrilika",
    color: "серый",
    faktura: "мелкие вкрапления",
  },
  {
    id: "354",
    name: "A203",
    price: "25830",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A203_Dusk_.jpg",
    category: "akrilika",
    color: "светлосерый",
    faktura: "мелкие вкрапления",
  },
  {
    id: "355",
    name: "A204",
    price: "25830",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A204_Sand_Stone_.jpg",
    category: "akrilika",
    color: "коричневый",
    faktura: "мелкие вкрапления",
  },
  {
    id: "356",
    name: "A209",
    price: "25830",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A209_Aurora_.jpg",
    category: "akrilika",
    color: "коричневый",
    faktura: "мелкие вкрапления",
  },
  {
    id: "357",
    name: "A210",
    price: "25830",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A210_Eclipse_.jpg",
    category: "akrilika",
    color: "светлосерый",
    faktura: "мелкие вкрапления",
  },
  {
    id: "358",
    name: "A213",
    price: "25830",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A213_Beach_.jpg",
    category: "akrilika",
    color: "бежевый",
    faktura: "мелкие вкрапления",
  },
  {
    id: "359",
    name: "A222",
    price: "25830",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A222_Classic_Grey_.jpg",
    category: "akrilika",
    color: "серый",
    faktura: "мелкие вкрапления",
  },
  {
    id: "360",
    name: "A313",
    price: "25830",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A313_Frosty_White_.jpg",
    category: "akrilika",
    color: "бежевый",
    faktura: "мелкие вкрапления",
  },
  {
    id: "361",
    name: "A401",
    price: "25830",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A401_Clio_.jpg",
    category: "akrilika",
    color: "белый",
    faktura: "мелкие вкрапления",
  },
  {
    id: "362",
    name: "A412",
    price: "25830",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A412_Slancio_Grey_.jpg",
    category: "akrilika",
    color: "серый",
    faktura: "мелкие вкрапления",
  },
  {
    id: "363",
    name: "A413",
    price: "25830",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A413_Slancio_Bone_.jpg",
    category: "akrilika",
    color: "бежевый",
    faktura: "мелкие вкрапления",
  },
  {
    id: "364",
    name: "A511",
    price: "25830",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A511_Rosa_Zarci_.jpg",
    category: "akrilika",
    color: "коричневый",
    faktura: "мелкие вкрапления",
  },
  {
    id: "365",
    name: "A512",
    price: "25830",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A512_Sand_Storm_.jpg",
    category: "akrilika",
    color: "коричневый",
    faktura: "мелкие вкрапления",
  },
  {
    id: "366",
    name: "A802",
    price: "25830",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A802_New_Aurora_.jpg",
    category: "akrilika",
    color: "бежевый",
    faktura: "мелкие вкрапления",
  },
  {
    id: "367",
    name: "A837",
    price: "25830",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A837_Abalone_.jpg",
    category: "akrilika",
    color: "бежевый",
    faktura: "мелкие вкрапления",
  },
  {
    id: "368",
    name: "A002",
    price: "27502",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A002_Tambora_.jpg",
    category: "akrilika",
    color: "",
    faktura: "мелкие вкрапления",
  },
  {
    id: "369",
    name: "A003",
    price: "27502",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A003_Casera_.jpg",
    category: "akrilika",
    color: "коричневый",
    faktura: "мелкие вкрапления",
  },
  {
    id: "370",
    name: "A128",
    price: "27502",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A128_Silver_Glam_.jpg",
    category: "akrilika",
    color: "коричневый",
    faktura: "мелкие вкрапления",
  },
  {
    id: "371",
    name: "A129",
    price: "27502",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A129_Shadow_Grey.jpg",
    category: "akrilika",
    color: "светлосерый",
    faktura: "мелкие вкрапления",
  },
  {
    id: "372",
    name: "A136",
    price: "27502",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A136_Onyx_Grey_.jpg",
    category: "akrilika",
    color: "серый",
    faktura: "мелкие вкрапления",
  },
  {
    id: "373",
    name: "A414",
    price: "27502",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A414_Black_Frost_.jpg",
    category: "akrilika",
    color: "черный",
    faktura: "мелкие вкрапления",
  },
  {
    id: "374",
    name: "A518",
    price: "27502",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A518_Savannah_.jpg",
    category: "akrilika",
    color: "бежевый",
    faktura: "мелкие вкрапления",
  },
  {
    id: "375",
    name: "A701",
    price: "27502",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A701_Platinum_.jpg",
    category: "akrilika",
    color: "серый",
    faktura: "мелкие вкрапления",
  },
  {
    id: "376",
    name: "A729",
    price: "27502",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A729_Ivory_Melange_.jpg",
    category: "akrilika",
    color: "светлосерый",
    faktura: "мелкие вкрапления",
  },
  {
    id: "377",
    name: "A784",
    price: "27502",
    image: "../../public/CalcImages/StoneTypes/Akrilka/A784_Cocoa_Brown_.jpg",
    category: "akrilika",
    color: "коричневый",
    faktura: "мелкие вкрапления",
  },
  {
    id: "378",
    name: "DA066",
    price: "40124",
    image:
      "../../public/CalcImages/StoneTypes/Akrilka/DA066_Grey_Horse_1600px.jpg",
    category: "akrilika",
    color: "светлосерый",
    faktura: "разводы",
  },
  {
    id: "379",
    name: "DA204",
    price: "40124",
    image:
      "../../public/CalcImages/StoneTypes/Akrilka/DA204_Shadows_1600px.jpg",
    category: "akrilika",
    color: "светлосерый",
    faktura: "мелкие вкрапления",
  },
  {
    id: "380",
    name: "DA217",
    price: "40124",
    image:
      "../../public/CalcImages/StoneTypes/Akrilka/DA217_Smoky_Stone_1600px.jpg",
    category: "akrilika",
    color: "светлосерый",
    faktura: "разводы",
  },
  {
    id: "381",
    name: "DA218",
    price: "40124",
    image:
      "../../public/CalcImages/StoneTypes/Akrilka/DA218_Zebrano_White_1600px.jpg",
    category: "akrilika",
    color: "светлосерый",
    faktura: "разводы",
  },
  {
    id: "382",
    name: "DA219",
    price: "40124",
    image:
      "../../public/CalcImages/StoneTypes/Akrilka/DA219_Zebrano_Cream_1600px.jpg",
    category: "akrilika",
    color: "светлосерый",
    faktura: "разводы",
  },
  {
    id: "383",
    name: "DA220",
    price: "40124",
    image:
      "../../public/CalcImages/StoneTypes/Akrilka/DA220_Zebrano_Beige_1600px.jpg",
    category: "akrilika",
    color: "",
    faktura: "разводы",
  },
  {
    id: "384",
    name: "DA221",
    price: "40124",
    image:
      "../../public/CalcImages/StoneTypes/Akrilka/DA221_Zebrano_Gold_1600px.jpg",
    category: "akrilika",
    color: "коричневый",
    faktura: "разводы",
  },
  {
    id: "385",
    name: "DA222",
    price: "40124",
    image:
      "../../public/CalcImages/StoneTypes/Akrilka/DA222_Zebrano_Rustic_1600px.jpg",
    category: "akrilika",
    color: "коричневый",
    faktura: "разводы",
  },
  {
    id: "386",
    name: "DA223",
    price: "40124",
    image:
      "../../public/CalcImages/StoneTypes/Akrilka/DA223_Silver_Rock_1600px.jpg",
    category: "akrilika",
    color: "серый",
    faktura: "разводы",
  },
  {
    id: "387",
    name: "DA224",
    price: "40124",
    image: "../../public/CalcImages/StoneTypes/Akrilka/DA224_Basalt_1600px.jpg",
    category: "akrilika",
    color: "коричневый",
    faktura: "разводы",
  },
  {
    id: "388",
    name: "DA225",
    price: "40124",
    image:
      "../../public/CalcImages/StoneTypes/Akrilka/DA225_White_Cloud_1600px.jpg",
    category: "akrilika",
    color: "белый",
    faktura: "разводы",
  },
  {
    id: "389",
    name: "DA226",
    price: "40124",
    image:
      "../../public/CalcImages/StoneTypes/Akrilka/DA226_Greige_Mist_1600px.jpg",
    category: "akrilika",
    color: "светлосерый",
    faktura: "разводы",
  },
  {
    id: "390",
    name: "DA227",
    price: "40124",
    image:
      "../../public/CalcImages/StoneTypes/Akrilka/DA227_Marmoreal_1600px.jpg",
    category: "akrilika",
    color: "светлосерый",
    faktura: "разводы",
  },
  {
    id: "391",
    name: "DA228",
    price: "40124",
    image:
      "../../public/CalcImages/StoneTypes/Akrilka/DA228_Carrara_1600px.jpg",
    category: "akrilika",
    color: "серый",
    faktura: "разводы",
  },
  {
    id: "392",
    name: "DA229",
    price: "40124",
    image:
      "../../public/CalcImages/StoneTypes/Akrilka/DA229_Cream_White_1600px.jpg",
    category: "akrilika",
    color: "светлосерый",
    faktura: "разводы",
  },
  {
    id: "393",
    name: "DA230",
    price: "40124",
    image:
      "../../public/CalcImages/StoneTypes/Akrilka/DA230_Fine_Wood_1600px.jpg",
    category: "akrilika",
    color: "",
    faktura: "разводы",
  },
  {
    id: "394",
    name: "DA231",
    price: "40124",
    image:
      "../../public/CalcImages/StoneTypes/Akrilka/DA231_Night_Sky_1600px.jpg",
    category: "akrilika",
    color: "серый",
    faktura: "разводы",
  },
  {
    id: "395",
    name: "DA232",
    price: "40124",
    image: "../../public/CalcImages/StoneTypes/Akrilka/DA232_Dune_1600px.jpg",
    category: "akrilika",
    color: "коричневый",
    faktura: "разводы",
  },
];
